### ISSUE TITLE
backslashing certain characters in the StringsFolder string (path) in config.json gives error when starting LocalizationTool

### ISSUE THREAD

**Issue by mhudec** [OwlcatGames/LocalizationTool#1]
Using backslashes (because Windows-style paths) with certain characters in StringsFolder in config.json can create issues during startup of the tool, e.g. having "StringsFolder": "d:\WH40KRT\WhRtModificationTemplate\Strings" gives error window with "'W' is an invalid escapable characted within a JSON string. The string should be correctly escaped. Path: $.StringsFolder | LineNumber: 5 | BytePositionInLine: 23." and then few lines from what looks like a stack/backtrace.

Well, yes, \W (and \w) and also \S (and \s) I remember from regular expressions, so I guess something inside breaks down because of this...

... anyway, easily fixable by either escaping the backslashes, e.g. "d:\\\WH40KRT\\\WhRtModificationTemplate\\\Strings", works, or by changing to slashes (like Unix-style paths), e.g. "d:/WH40KRT/WhRtModificationTemplate/Strings", works too.

**Comment by vmchar** [comment]
@mhudec  have made changes a time ago. Is issue reproducable in the latest build?

**Comment by mhudec** [comment]
@vmchar - I had this issue with v201, with newer v202 (that got released few days later) it is OK, the path in the config.json gets changed from \ to / automatically after I start the program. Thanks!

P.S. ... v203 seems to offer only source code ZIP archives for download so far in the releases.

**Comment by mhudec** [comment]
v206 is OK too (replaces \ with /). Thank you.
